version: '3.8'
services:
  eureka:
    build: ./server-eureka
    image: xunkutech/server-eureka:latest
    container_name: server-eureka
    hostname: server-eureka
    environment:
      - "TZ=Asia/Shanghai"
      - "SERVER_PORT=8761"
      - "EUREKA_HOSTNAME=server-eureka"
      - "EUREKA_PORT=8761"
    restart: always
    networks:
      - "backend"
    ports:
      - "8761:8761"
  config:
    build: ./server-config
    image: xunkutech/server-config:latest
    container_name: server-config
    hostname: server-config
    environment:
      - "TZ=Asia/Shanghai"
      - "SERVER_PORT=8888"
      - "EUREKA_HOSTNAME=server-eureka"
      - "EUREKA_PORT=8761"
    restart: on-failure
    networks:
      - "backend"
    ports:
      - "8888:8888"
    links: 
      - eureka
  zuul:
    build: ./server-zuul
    image: xunkutech/server-zuul:latest
    container_name: server-zuul
    hostname: server-zuul
    environment:
      - "TZ=Asia/Shanghai"
      - "SERVER_PORT=9000"   
      - "EUREKA_HOSTNAME=server-eureka"
      - "EUREKA_PORT=8761"
    restart: on-failure
    networks:
      - "backend"
    ports:
      - "9000:9000"
    links: 
      - eureka
  book:
    build: ./service-book
    image: xunkutech/service-book:latest
    container_name: service-book
    hostname: service-book
    environment:
      - "TZ=Asia/Shanghai"
      - "SERVER_PORT=9001"   
      - "EUREKA_HOSTNAME=server-eureka"
      - "EUREKA_PORT=8761"
    restart: on-failure
    networks:
      - "backend"
    ports:
      - "9001:9001"
    links: 
      - eureka
  library:
    build: ./service-library
    image: xunkutech/service-library:latest
    container_name: service-library
    hostname: service-library
    environment:
      - "TZ=Asia/Shanghai"
      - "SERVER_PORT=9002"   
      - "EUREKA_HOSTNAME=server-eureka"
      - "EUREKA_PORT=8761"
    restart: on-failure
    networks:
      - "backend"
    ports:
      - "9002:9002"
    links: 
      - eureka
  read:
    build:
      context: ./service-read
    image: xunkutech/service-read:latest
    container_name: service-read
    hostname: service-read
    environment:
      - "TZ=Asia/Shanghai"
      - "SERVER_PORT=9003"   
      - "EUREKA_HOSTNAME=server-eureka"
      - "EUREKA_PORT=8761"
    restart: on-failure
    networks:
      - "backend"
    ports:
      - "9003:9003"
    links: 
      - eureka
  helloworld:
    build:
      context: ./frontend-helloworld
    image: xunkutech/frontend-helloworld:latest
    container_name: frontent
    environment:
      - "TZ=Asia/Shanghai"
      - "SERVER_PORT=8080"
      - "BAIDU_URI=www.baidu.com"
    ports:
      - "8000:8080"
    restart: on-failure
    networks:
      - "backend"
networks:
  backend:
    driver: bridge