version: '3'

services:
  scan:
    image:  sonarsource/sonar-scanner-cli:4.7
    environment:
      - "TZ=Asia/Shanghai"
      - "SONAR_SCANNER_OPTS=-Dsonar.host.url=${SONAR_HOST} -Dsonar.projectKey=${SONAR_PROJECT} -Dsonar.login=${SONAR_LOGIN} -Dsonar.source=/usr/src -Dsonar.java.binaries=/usr/src ${SONAR_OPTS:-}"
    volumes:
      - ${PROJECT_PATH}:/usr/src
      - sonarscanner_cache:/opt/sonar-scanner/.sonar/cache
    ulimits:
      nproc: 65535
      nofile:
        soft: 50000
        hard: 50000

volumes:
  sonarscanner_cache:
    name: sonarscanner_cache