server.port: 9001
spring:
  application.name: server-eureka

eureka:
  server:
    evictionIntervalTimerInMs: 3000
    response-cache-update-interval-ms: 3000
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
