server.port: 9001
spring:
  application.name: server-eureka

eureka:
  server:
    evictionIntervalTimerInMs: 3000
    responseCacheUpdateIntervalMs: 3000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
