{{- range $name, $value := .Values.microServices}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" (include "sanyi.fullname" $) $name }}
  labels:
    {{- include "sanyi.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: {{ $value.containerPort }}
  selector:
    {{- include "sanyi.selectorLabels" $ | nindent 4 }}
    app: {{ printf "%s-%s" (include "sanyi.fullname" $) $name }}
{{- end }}