server.port: ${SERVER_PORT}

eureka:
  client:
    serviceUrl.defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registryFetchIntervalSeconds: 5
    # Unlike the Eureka server, we do want to register this service
    registerWithEureka: true
    # We also want to get a copy of the registry to cache
    fetchRegistry: true
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true