server.port: ${SERVER_PORT}

spring:
  profiles.active: native
  application.name: server-config
  cloud.config.server:
    composite.type: composite
    native.search-locations: file://///tmp

eureka:
  client:
    serviceUrl.defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registryFetchIntervalSeconds: 5
instance:
  leaseRenewalIntervalInSeconds: 5
  preferIpAddress: true